name: Docker Image

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE_TAG: 1.0.0
  DOCKER_SPECIFIC_IMAGE_TAG: ubuntu_git_ruby_cron

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Build Image
      run: |
        docker build $DOCKER_IMAGE_TAG/. -t zaimramlan/ubuntu-git-ruby-cron:latest
        docker image save zaimramlan/ubuntu-git-ruby-cron:latest -o docker-image.tar
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: docker-image.tar

  push:
    name: Push Image to Registry
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image
    - name: Tag Image
      run: |
        docker image import docker-image.tar zaimramlan/ubuntu-git-ruby-cron:latest
        docker tag zaimramlan/ubuntu-git-ruby-cron:latest zaimramlan/ubuntu-git-ruby-cron:$DOCKER_IMAGE_TAG
        docker tag zaimramlan/ubuntu-git-ruby-cron:latest zaimramlan/ubuntu-git-ruby-cron:$DOCKER_SPECIFIC_IMAGE_TAG
    - name: Push Images to Registry
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push zaimramlan/ubuntu-git-ruby-cron:latest
        docker push zaimramlan/ubuntu-git-ruby-cron:$DOCKER_IMAGE_TAG
        docker push zaimramlan/ubuntu-git-ruby-cron:$DOCKER_SPECIFIC_IMAGE_TAG
